import "./globals.scss";
import styles from "./page.module.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>Header would go here</header>

        {children}

        <footer className={styles.footer}>Footer would go here</footer>
      </body>
    </html>
  );
}
